# Generated by Django 5.2.10 on 2026-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=4, verbose_name='حداقل طول رمز عبور')),
                ('require_uppercase', models.BooleanField(default=False, verbose_name='نیاز به حروف بزرگ')),
                ('require_digit', models.BooleanField(default=False, verbose_name='نیاز به عدد')),
                ('require_special_char', models.BooleanField(default=False, verbose_name='نیاز به کاراکتر خاص')),
            ],
        ),
    ]
