# Generated by Django 5.2.10 on 2026-01-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminpolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPolicy',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
