# Generated by Django 5.2.10 on 2026-02-13 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_downloaderfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=8, verbose_name='حداقل طول رمز')),
                ('require_uppercase', models.BooleanField(default=True, verbose_name='نیاز به حروف بزرگ')),
                ('require_digit', models.BooleanField(default=True, verbose_name='نیاز به عدد')),
                ('require_special_char', models.BooleanField(default=False, verbose_name='نیاز به کاراکتر خاص')),
            ],
            options={
                'verbose_name': 'سیاست رمز عبور',
                'verbose_name_plural': 'سیاست\u200cهای رمز عبور',
            },
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='button_size',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
