# Generated by Django 5.2.10 on 2026-03-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_blocked_at_userprofile_is_blocked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='save_to_cloud',
            field=models.BooleanField(default=True, verbose_name='ذخیره در فضای ابری'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='sent_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupleader',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
