# Generated by Django 5.2.10 on 2026-04-05 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fileactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileactionlog',
            options={'ordering': ['-action_time']},
        ),
        migrations.AlterField(
            model_name='fileactionlog',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fileactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='fileactionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='min_password_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='require_digit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='require_special_char',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='require_uppercase',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='save_to_cloud',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
    ]
