# Generated by Django 5.2.10 on 2026-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_file_fileshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='button_size',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
